import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "@/lib/font";
import Header from "@/components/navbar/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Founders Friday",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className}  min-h-screen flex flex-col bg-[#FDF7FF] antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
